require "spec"
require "../src/crystalg/data_structures/*"
require "../src/crystalg/data_structures/trees/*"
require "../src/crystalg/graph/*"
require "../src/crystalg/graph/searching/*"
require "../src/crystalg/strings/*"
require "../src/crystalg/number_theory/*"
require "../src/crystalg/geometry/*"
