require "spec"
require "../src/crystalg/data_structures/*"
require "../src/crystalg/graph/*"
require "../src/crystalg/graph/flow/*"
require "../src/crystalg/graph/connected_components/*"
require "../src/crystalg/strings/*"
require "../src/crystalg/number_theory/*"
require "../src/crystalg/geometry/*"
