name: crystalg

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest}
          - {os: macos-latest}
          - {os: windows-latest}
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - uses: oprypin/install-crystal@v1
      with:
        crystal: 1.0.0
    - run: shards install
    - run: crystal spec
    - run: crystal tool format && git diff --exit-code
      if: matrix.crystal == 'latest'
    - run: crystal docs
    - name: Deploy document
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        keep_files: true